### ISSUE TITLE
recover leoh new tab extension

### ISSUE THREAD

**Issue by urfausto** [code-for-charity/Wish-Factory#2]
https://github.com/Bobrobot1/Leoh/issues/1#issuecomment-948380939

-fix zen mode
-stop hiding lists when clicking anywhere inside tab frame and unless you click on them directly
-remove ad frame at the bottom
-add background pix
-fix weather forecast

**Comment by urfausto** [comment]
just found this brand new shiny project which is even open source: https://chrome.google.com/webstore/detail/tabliss-a-beautiful-new-t/hipekcciheckooncpjeljhnekcoolahp

@ImprovedTube should invite them to the organization...

**Comment by ImprovedTube** [comment]
> @ImprovedTube should invite them to the organization...

😅

- hi @Joelshepherd! 😊  Our [project](https://github.com/code-for-charity/ImprovedTube-for-YouTube) is interesting 🤫 as of 500 000 users & losing its sole developer. - He also made a [library shared in his 10+ extensions](https://github.com/code-for-charity/satus), yet waiting for the first other developers to ever try it.
